#fileUploadPath=E:/work/20171227/
fileUploadPath=D:/work/fileUpload/
customerUploadPath=E:/eclipse-workspace/rg-aws/WebContent/assets/images/customer_logo/
imageUploadPath=D:/eclipse-workspace/rg-aws/WebContent/assets/imageUploaded/

#redis.host=jisblee.me
redis.host=localhost
redis.port=6379
redis.password=jiseob9123
#redis.password=
redis.maxInactiveIntervalInSeconds=50000



app.languages[0]=en
app.countries[0]=US
app.languages[1]=ko
app.countries[1]=KR
app.languages[2]=ja
app.countries[2]=JP
app.languages[3]=zn
app.countries[3]=CN
